### ISSUE TITLE
Can I use flowdock to score existing co-modelled protein-ligand structures

### ISSUE THREAD

**Issue by hopanoid** [BioinfoMachineLearning/FlowDock#1]
For example, I have 

Protein:A
Ligand:B

And, I use Alphafold3, to predict the complex of A, B. Now, I have alphafold3 output pdb file "AB_model.pdb", and I want to compute the B ligand's affinity score for protein A providing the alphafold's output file as input. Is there a way to score the alphafold's predicted protein-ligand complexes using flowdock?

**Comment by amorehead** [comment]
Hi, @hopanoid.

Yes, this is possible with the current version of the codebase. In fact, this is similar to what my team and I did (with some success) in the recent CASP16 competition. To do so, you first need to separate AF3's predicted protein chain(s) into a separate (singular) PDB file, and similarly, you need to separate AF3's predicted ligand chain(s) into a separate SDF file (combining each multi-ligand into a single `Chem.Mol` object via `Chem.CombineMols()` before exporting this singular SDF file). If you'd like some code to reference for one way to do this, please see v0.6.0 of the [PoseBench codebase](https://github.com/BioinfoMachineLearning/PoseBench/tree/0.6.0?tab=readme-ov-file#how-to-run-inference-with-alphafold-3) (namely the `af3_output_extraction.py` script) to see how I was able to successfully extract AF3's predicted (singular) mmCIF files into separate protein PDB and ligand SDF files (for each ligand). Once you have done this, you can do something like the following to provide these separate protein (PDB) and ligand (SDF) files to FlowDock for affinity prediction.

```bash
python flowdock/sample.py ckpt_path=checkpoints/esmfold_prior_paper_weights_EMA.ckpt model.cfg.prior_type=esmfold sampling_task=batched_structure_sampling input_receptor='$PATH_TO_PROTEIN_PDB' input_ligand='$PATH_TO_LIGAND_SDF' input_template='$PATH_TO_PROTEIN_PDB' sample_id='$PDBID' out_path='./$PDBID_sampled_structures/' n_samples=1 chunk_size=1 num_steps=40 sampler=VDODE sampler_eta=1.0 start_time='1.0' use_template=true separate_pdb=true visualize_sample_trajectories=false auxiliary_estimation_only=true esmfold_chunk_size=null trainer=gpu
```

For reference, the key logic via which this is possible can be found [here](https://github.com/BioinfoMachineLearning/FlowDock/blob/4749a588c67634483deb4546df4bc67a0a9f9bac/flowdock/utils/sampling_utils.py#L197).

**Comment by hopanoid** [comment]
Thanks @amorehead

**Comment by amorehead** [comment]
@hopanoid, let me know if you have any follow up questions. In the meantime, I'll close this issue, but feel free to reopen if and whenever you'd like.

**Comment by MilSpaine** [comment]
Hi Alex!
This solution works great for me.  I was just wondering if there was any settings that could boost the calculations. 

Thanks in advance.

**Comment by amorehead** [comment]
Hi, @MilSpaine. Could you clarify what you mean by "boost the calculations"? Do you mean the speed of calculating binding affinities?

**Comment by MilSpaine** [comment]
Exactly!
Sorry if I was not writing  with clarity

**Comment by amorehead** [comment]
@MilSpaine, are you already using FlowDock's batched sampling mode as documented [here](https://github.com/BioinfoMachineLearning/FlowDock?tab=readme-ov-file#how-to-predict-new-protein-ligand-complex-structures-and-their-affinities-using-flowdock)?

**Comment by MilSpaine** [comment]
Great idea!  I don't know why I did not think about this. Thanks Alex!!

**Comment by MilSpaine** [comment]
It did speed up a lot the affinity prediction calculations. 
I believe that affinity prediccions are key.   Thanks for including it in your work. 🙏

**Comment by amorehead** [comment]
@MilSpaine 🚀 Glad to hear it!
