### ISSUE TITLE
Where is the data/split folder??

### ISSUE THREAD

**Issue by ShuoAndy** [BioinfoMachineLearning/FlowDock#2]
In your `.gitignore` file, it appears that the `data/splits` folder should not be ignored (and thus should be uploaded to the code repository). However, I do not see this folder in your repository. This causes your `flowdock/eval.py` to fail to run, resulting in the error: "No such file or directory: '***/FlowDock/data/splits/timesplit_test'."

**Comment by amorehead** [comment]
Hi, @ShuoAndy. Thanks for pointing this issue out! For some odd reason, my local IDE was saying the `data` directory was already committed to this repository's `main` branch, but apparently, that wasn't the case. In [this new commit](https://github.com/BioinfoMachineLearning/FlowDock/commit/18a0d81fa204a38ee4804e51dc7024d5de5f41e1), I've just pushed the full `data` directory in including the subdirectory `splits`. Let me know if you run into any other issues!
